project:
  type: website
  preview:
    port: 7117

website:
  title: "Digital History in Sweden"
  navbar:
    left:
      - href: conference.qmd
      - href: projects.qmd
    right:
      - about.qmd
    pinned: true
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/mathjoha/DigitalHistorySweden
          - text: Report a Bug
            href:  https://bugs.com


  page-footer:
    left: "Copyright 2024, Mathias Johansson"
    right:
      - icon: github
        href: https://github.com/
  repo-url: https://github.com/mathjoha/DigitalHistorySweden
  repo-actions: [issue]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
