project:
  type: website
  preview:
    port: 7117

website:
  title: "Digital History in Sweden"
  navbar:
    left:
      - href: conference.qmd
    right:
      - about.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
